# Generated by Django 3.1.2 on 2020-10-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_auto_20201029_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
